name: Docker Build and Release
on: [ push ]
env:
  #### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tipp: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  # Test
  GITHUB_ACCESSTOKEN: ${{ secrets.PET_CLINIC_SECRET }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Compile, build and push
        run: |
          #### AUFGABE COMPILE, DOCKER BUILD UND PUSH
          # hier ist Platz für maven package und docker build

          # 1. Das Projekt mit Maven bauen (Erstellt die .jar Datei im target/ Ordner)
          ./mvnw clean package

          # 2. Bei Docker einloggen (Nutzt das verschlüsselte Secret aus den Env-Variablen oben)
          docker login ghcr.io -u ${{ github.actor }} -p $GITHUB_ACCESSTOKEN

          # 3. Das bereitgestellte Dockerfile bauen (kleingeschrieben!)
          docker build -t ghcr.io/scheuffen/petclinic:latest .

          # 4. Das Docker-Image in die GitHub-Package-Registry pushen
          docker push ghcr.io/scheuffen/petclinic:latest

